name: Release Plugin

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Only run on the original repo, not on forks
    if: github.repository == 'bjonnh/obsidian-barcoding'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Create release zip
        run: |
          mkdir barcoding
          cp main.js manifest.json styles.css versions.json barcoding
          zip -r obsidian-barcoding-${{ github.ref_name }}.zip barcoding

      - name: Create GitHub Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: |
            obsidian-barcoding-${{ github.ref_name }}.zip
          draft: false
          prerelease: false
